version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip *.py mock data.json
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://bank-transactions-cicd-builds
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name bank-transactions-lambda-generate-json --s3-bucket bank-transactions-cicd-builds --s3-key deployment_package.zip
      - aws lambda invoke --function-name bank-transactions-lambda-generate-json --payload '{}' response.json
      - echo "Deployment complete!"